import Head from 'next/head'
import Image from 'next/image'
import Contact from './components/Contact'
import Hero from './components/Hero'
import Slider from './components/Slider'
import { SliderData } from './components/SliderData'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Landing Page Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero heading='Website Freelancer' message='I build Landing Pages' />
        <Slider slides={SliderData}/>
        <Contact />
        </div>
        )
}
